version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APACHE_RUN_USER=www-data
        volumes:
          - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        ports:
          - 6080:80
        working_dir: ${APP_PATH_CONTAINER}



